// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIjzquXc8ju3keAyZJx3IyAzbv2nt_cFk',
    appId: '1:737808323980:web:133f9ba1679f2927b072a9',
    messagingSenderId: '737808323980',
    projectId: 'transco-e8838',
    authDomain: 'transco-e8838.firebaseapp.com',
    storageBucket: 'transco-e8838.firebasestorage.app',
    measurementId: 'G-JGNG0YC9T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXAK7bYUn2V-ZJfAKwIk_mIlZ6In2ayho',
    appId: '1:737808323980:android:93031c92ae79d9deb072a9',
    messagingSenderId: '737808323980',
    projectId: 'transco-e8838',
    storageBucket: 'transco-e8838.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnPfgKWoyQW6chQvApdZ4CJR1LZAgwzfs',
    appId: '1:737808323980:ios:1e39cac319f7dabcb072a9',
    messagingSenderId: '737808323980',
    projectId: 'transco-e8838',
    storageBucket: 'transco-e8838.firebasestorage.app',
    iosBundleId: 'com.example.transco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnPfgKWoyQW6chQvApdZ4CJR1LZAgwzfs',
    appId: '1:737808323980:ios:1e39cac319f7dabcb072a9',
    messagingSenderId: '737808323980',
    projectId: 'transco-e8838',
    storageBucket: 'transco-e8838.firebasestorage.app',
    iosBundleId: 'com.example.transco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIjzquXc8ju3keAyZJx3IyAzbv2nt_cFk',
    appId: '1:737808323980:web:ac5ca168413793afb072a9',
    messagingSenderId: '737808323980',
    projectId: 'transco-e8838',
    authDomain: 'transco-e8838.firebaseapp.com',
    storageBucket: 'transco-e8838.firebasestorage.app',
    measurementId: 'G-969HXD1G5R',
  );
}
